### ISSUE TITLE
code ko kei funtionality nei xaina k ho esto j pai tei 

### ISSUE THREAD

**Issue by senny789** [Sulash-Manandhar/UserManagementSystem#1]
<img width="625" alt="Screen Shot 2022-06-13 at 2 30 17 PM" src="https://user-images.githubusercontent.com/51574734/173315573-aab47f05-e02d-483a-95e1-0a49fe79025b.png">

**Comment by Sulash-Manandhar** [comment]
This feature will be implemented soon in future. Thank you for your concern.
